### ISSUE TITLE
How do you configure redis server?

### ISSUE THREAD

**Issue by soujiro0725** [karafka/karafka-example-app#27]
How do you specify IP and namespace of redis server?
karafka-sidekiq-backend seems to look for 127.0.0.1:6379 by default.

Adding sidekiq.rb to config/initializers

```
Sidekiq.configure_server do |config|
    config.redis = { url: 'redis://192.168.99.100:6379', namespace: "sidekiq" }
end

Sidekiq.configure_client do |config|
    config.redis = { url: 'redis://192.168.99.100:6379', namespace: "sidekiq" }
end
```

does not seem to work.

**Comment by mensfeld** [comment]
Hey @soujiro0725 checking ;)

**Comment by mensfeld** [comment]
@soujiro0725 it seems to work on my side:

1. Added a directory called ```initializers``` in the config directory
2. Created a config exactly as yours
3. Started worker by using ```bundle exec karafka w```

And this is what I get:

```bash
Starting Karafka worker
Karafka framework version: 1.1.0
Application client id: example_app
Backend: inline
Batch fetching: true
Batch consuming: false
Boot file: /home/mencio/Software/Github/karafka/example-app/karafka.rb
Environment: development
Kafka seed brokers: ["kafka://127.0.0.1:9092"]
bundle exec sidekiq -e development -r /home/mencio/Software/Github/karafka/example-app/karafka.rb -C /home/mencio/Software/Github/karafka/example-app/config/sidekiq.yml
2017-11-23T07:58:55.750Z 6992 TID-707yw INFO: Booting Sidekiq 5.0.5 with redis options {:url=>"redis://192.168.99.100:6379", :id=>"Sidekiq-server-PID-6992"}


         m,
         `$b
    .ss,  $$:         .,d$
    `$$P,d$P'    .,md$P"'
     ,$$$$$bmmd$$$P^'
   .d$$$$$$$$$$P'
   $$^' `"^$$$'       ____  _     _      _    _
   $:     ,$$:       / ___|(_) __| | ___| | _(_) __ _
   `b     :$$        \___ \| |/ _` |/ _ \ |/ / |/ _` |
          $$:         ___) | | (_| |  __/   <| | (_| |
          $$         |____/|_|\__,_|\___|_|\_\_|\__, |
        .d$$                                       |_|

2017-11-23T07:58:55.808Z 6992 TID-707yw INFO: Running in ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
2017-11-23T07:58:55.808Z 6992 TID-707yw INFO: See LICENSE and the LGPL-3.0 for licensing details.
2017-11-23T07:58:55.808Z 6992 TID-707yw INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
Error connecting to Redis on 192.168.99.100:6379 (Errno::ECONNREFUSED)
/gems/redis-4.0.1/lib/redis/client.rb:344:in `rescue in establish_connection'
/gems/redis-4.0.1/lib/redis/client.rb:329:in `establish_connection'
/gems/redis-4.0.1/lib/redis/client.rb:99:in `block in connect'
/gems/redis-4.0.1/lib/redis/client.rb:291:in `with_reconnect'
/gems/redis-4.0.1/lib/redis/client.rb:98:in `connect'
/gems/redis-4.0.1/lib/redis/client.rb:363:in `ensure_connected'
/gems/redis-4.0.1/lib/redis/client.rb:219:in `block in process'
/gems/redis-4.0.1/lib/redis/client.rb:304:in `logging'
/gems/redis-4.0.1/lib/redis/client.rb:218:in `process'
/gems/redis-4.0.1/lib/redis/client.rb:118:in `call'
/gems/redis-4.0.1/lib/redis.rb:274:in `block in info'
/gems/redis-4.0.1/lib/redis.rb:45:in `block in synchronize'
/home/mencio/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/gems/redis-4.0.1/lib/redis.rb:45:in `synchronize'
/gems/redis-4.0.1/lib/redis.rb:273:in `info'
/gems/sidekiq-5.0.5/lib/sidekiq.rb:113:in `block in redis_info'
/gems/sidekiq-5.0.5/lib/sidekiq.rb:95:in `block in redis'
/gems/connection_pool-2.2.1/lib/connection_pool.rb:64:in `block (2 levels) in with'
/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `handle_interrupt'
/gems/connection_pool-2.2.1/lib/connection_pool.rb:63:in `block in with'
/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
/gems/sidekiq-5.0.5/lib/sidekiq.rb:92:in `redis'
/gems/sidekiq-5.0.5/lib/sidekiq.rb:106:in `redis_info'
/gems/sidekiq-5.0.5/lib/sidekiq/cli.rb:81:in `run'
/gems/sidekiq-5.0.5/bin/sidekiq:12:in `<top (required)>'
/bin/sidekiq:23:in `load'
/bin/sidekiq:23:in `<main>'
/bin/ruby_executable_hooks:15:in `eval'
/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mensfeld** [comment]
Hey @soujiro0725 just to be sure, I've prepared an example branch for you with both things you need: https://github.com/karafka/karafka-example-app/tree/sidekiq-config

you can see my changes here: https://github.com/karafka/karafka-example-app/compare/sidekiq-config

Could you please verify that this problem persists with this branch?

**Comment by soujiro0725** [comment]
Thanks. It did work with that branch.
Looks like my network problem.  Sorry...

**Comment by mensfeld** [comment]
@soujiro0725 no worries :+1: I will keep that branch in repo for couple more days just in case you'll need it. Good luck with Karafka!
